// Code generated by MockGen. DO NOT EDIT.
// Source: network/setup_network_interfaces.go

// Package mock_network is a generated GoMock package.
package mock_network

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockNetworkService is a mock of NetworkService interface
type MockNetworkService struct {
	ctrl     *gomock.Controller
	recorder *MockNetworkServiceMockRecorder
}

// MockNetworkServiceMockRecorder is the mock recorder for MockNetworkService
type MockNetworkServiceMockRecorder struct {
	mock *MockNetworkService
}

// NewMockNetworkService creates a new mock instance
func NewMockNetworkService(ctrl *gomock.Controller) *MockNetworkService {
	mock := &MockNetworkService{ctrl: ctrl}
	mock.recorder = &MockNetworkServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockNetworkService) EXPECT() *MockNetworkServiceMockRecorder {
	return m.recorder
}

// AddBridge mocks base method
func (m *MockNetworkService) AddBridge(br string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddBridge", br)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddBridge indicates an expected call of AddBridge
func (mr *MockNetworkServiceMockRecorder) AddBridge(br interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBridge", reflect.TypeOf((*MockNetworkService)(nil).AddBridge), br)
}

// ListBridges mocks base method
func (m *MockNetworkService) ListBridges() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBridges")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBridges indicates an expected call of ListBridges
func (mr *MockNetworkServiceMockRecorder) ListBridges() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBridges", reflect.TypeOf((*MockNetworkService)(nil).ListBridges))
}

// CheckBridgeHasInterface mocks base method
func (m *MockNetworkService) CheckBridgeHasInterface(bridgeName, ifcName string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckBridgeHasInterface", bridgeName, ifcName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckBridgeHasInterface indicates an expected call of CheckBridgeHasInterface
func (mr *MockNetworkServiceMockRecorder) CheckBridgeHasInterface(bridgeName, ifcName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckBridgeHasInterface", reflect.TypeOf((*MockNetworkService)(nil).CheckBridgeHasInterface), bridgeName, ifcName)
}

// GetBridgeInterfacesNames mocks base method
func (m *MockNetworkService) GetBridgeInterfacesNames(bridgeName string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBridgeInterfacesNames", bridgeName)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBridgeInterfacesNames indicates an expected call of GetBridgeInterfacesNames
func (mr *MockNetworkServiceMockRecorder) GetBridgeInterfacesNames(bridgeName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBridgeInterfacesNames", reflect.TypeOf((*MockNetworkService)(nil).GetBridgeInterfacesNames), bridgeName)
}

// CheckNetworkInterfaceExists mocks base method
func (m *MockNetworkService) CheckNetworkInterfaceExists(name string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckNetworkInterfaceExists", name)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckNetworkInterfaceExists indicates an expected call of CheckNetworkInterfaceExists
func (mr *MockNetworkServiceMockRecorder) CheckNetworkInterfaceExists(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckNetworkInterfaceExists", reflect.TypeOf((*MockNetworkService)(nil).CheckNetworkInterfaceExists), name)
}

// AddTap mocks base method
func (m *MockNetworkService) AddTap(tap string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTap", tap)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddTap indicates an expected call of AddTap
func (mr *MockNetworkServiceMockRecorder) AddTap(tap interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTap", reflect.TypeOf((*MockNetworkService)(nil).AddTap), tap)
}

// AddTapToBridge mocks base method
func (m *MockNetworkService) AddTapToBridge(br, tap string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTapToBridge", br, tap)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddTapToBridge indicates an expected call of AddTapToBridge
func (mr *MockNetworkServiceMockRecorder) AddTapToBridge(br, tap interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTapToBridge", reflect.TypeOf((*MockNetworkService)(nil).AddTapToBridge), br, tap)
}

// SetNIIP mocks base method
func (m *MockNetworkService) SetNIIP(ifc, ip, netmask string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetNIIP", ifc, ip, netmask)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetNIIP indicates an expected call of SetNIIP
func (mr *MockNetworkServiceMockRecorder) SetNIIP(ifc, ip, netmask interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNIIP", reflect.TypeOf((*MockNetworkService)(nil).SetNIIP), ifc, ip, netmask)
}

// FlushIPFromNI mocks base method
func (m *MockNetworkService) FlushIPFromNI(niName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FlushIPFromNI", niName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FlushIPFromNI indicates an expected call of FlushIPFromNI
func (mr *MockNetworkServiceMockRecorder) FlushIPFromNI(niName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FlushIPFromNI", reflect.TypeOf((*MockNetworkService)(nil).FlushIPFromNI), niName)
}

// TurnNIUp mocks base method
func (m *MockNetworkService) TurnNIUp(ifc string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TurnNIUp", ifc)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TurnNIUp indicates an expected call of TurnNIUp
func (mr *MockNetworkServiceMockRecorder) TurnNIUp(ifc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TurnNIUp", reflect.TypeOf((*MockNetworkService)(nil).TurnNIUp), ifc)
}

// TurnNIDown mocks base method
func (m *MockNetworkService) TurnNIDown(ifc string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TurnNIDown", ifc)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TurnNIDown indicates an expected call of TurnNIDown
func (mr *MockNetworkServiceMockRecorder) TurnNIDown(ifc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TurnNIDown", reflect.TypeOf((*MockNetworkService)(nil).TurnNIDown), ifc)
}

// DeleteNIC mocks base method
func (m *MockNetworkService) DeleteNIC(ifc string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNIC", ifc)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteNIC indicates an expected call of DeleteNIC
func (mr *MockNetworkServiceMockRecorder) DeleteNIC(ifc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNIC", reflect.TypeOf((*MockNetworkService)(nil).DeleteNIC), ifc)
}

// IsNIUp mocks base method
func (m *MockNetworkService) IsNIUp(ifcName string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsNIUp", ifcName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsNIUp indicates an expected call of IsNIUp
func (mr *MockNetworkServiceMockRecorder) IsNIUp(ifcName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsNIUp", reflect.TypeOf((*MockNetworkService)(nil).IsNIUp), ifcName)
}

// GetNetworkInterfaceIP mocks base method
func (m *MockNetworkService) GetNetworkInterfaceIP(ifcName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNetworkInterfaceIP", ifcName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNetworkInterfaceIP indicates an expected call of GetNetworkInterfaceIP
func (mr *MockNetworkServiceMockRecorder) GetNetworkInterfaceIP(ifcName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetworkInterfaceIP", reflect.TypeOf((*MockNetworkService)(nil).GetNetworkInterfaceIP), ifcName)
}
